### ISSUE TITLE
Public release checklist

### ISSUE THREAD

**Issue by DouglasOrr** [graphcore-research/pytorch-approx-topk#4]
From README; some of these may already be resolved:

- [x] integration as a PyTorch op, to support autograd and torch.compile()
- [ ] improved heuristic to decide whether to launch thread-per-bucket or block-per-bucket kernel
- [x] improvements to api

**Comment by oscarkey** [comment]
For now I'm leaving the heuristic as it is.
